package com.example.nexa.viewmodel

import android.app.Application
import android.content.ContentResolver
import android.net.Uri
import android.util.Log
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import com.example.nexa.data.UserPreferencesRepository
import com.example.nexa.data.local.ConversationDao
import com.example.nexa.data.local.ConversationMemory
import com.google.gson.Gson
import com.google.gson.reflect.TypeToken
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
import java.io.BufferedReader
import java.io.FileOutputStream
import java.io.InputStreamReader
import javax.inject.Inject

@HiltViewModel
class SettingsViewModel @Inject constructor(
    application: Application,
    private val conversationDao: ConversationDao,
    private val gson: Gson,
    private val userPreferencesRepository: UserPreferencesRepository
) : AndroidViewModel(application) {

    private val _operationStatus = MutableStateFlow<String?>(null)
    val operationStatus: StateFlow<String?> = _operationStatus.asStateFlow()

    private val _errorStatus = MutableStateFlow<String?>(null)
    val errorStatus: StateFlow<String?> = _errorStatus.asStateFlow()

    // Ollama IP State
    private val _ollamaIpAddress = MutableStateFlow(UserPreferencesRepository.DEFAULT_OLLAMA_IP)
    val ollamaIpAddress: StateFlow<String> = _ollamaIpAddress.asStateFlow()

    // TTS Enabled State
    private val _isTtsEnabled = MutableStateFlow(UserPreferencesRepository.DEFAULT_TTS_ENABLED)
    val isTtsEnabled: StateFlow<Boolean> = _isTtsEnabled.asStateFlow()

    init {
        viewModelScope.launch {
            userPreferencesRepository.ollamaIpAddressFlow.collect { ip ->
                _ollamaIpAddress.value = ip
            }
        }
        viewModelScope.launch {
            userPreferencesRepository.isTtsEnabledFlow.collect { enabled ->
                _isTtsEnabled.value = enabled
            }
        }
    }

    fun saveOllamaIpAddress(ipAddress: String) {
        viewModelScope.launch {
            // Basic validation, can be improved
            var finalIp = ipAddress.trim()
            if (!finalIp.startsWith("http://") && !finalIp.startsWith("https://")) {
                finalIp = "http://$finalIp"
            }
            if (finalIp.endsWith('/')) {
                finalIp = finalIp.dropLast(1)
            }
            userPreferencesRepository.saveOllamaIpAddress(finalIp)
            _operationStatus.value = "Ollama IP Address saved."
        }
    }

    fun saveTtsEnabled(isEnabled: Boolean) {
        viewModelScope.launch {
            userPreferencesRepository.saveTtsEnabled(isEnabled)
            _operationStatus.value = "TTS setting saved."
        }
    }

    fun exportMemories(uri: Uri) {
        viewModelScope.launch {
            try {
                val memories = conversationDao.getAllMemoriesList()
                if (memories.isEmpty()) {
                    _operationStatus.value = "No memories to export."
                    return@launch
                }
                val jsonString = gson.toJson(memories)
                val contentResolver = getApplication<Application>().contentResolver
                contentResolver.openFileDescriptor(uri, "w")?.use { parcelFileDescriptor ->
                    FileOutputStream(parcelFileDescriptor.fileDescriptor).use { outputStream ->
                        outputStream.write(jsonString.toByteArray())
                    }
                }
                _operationStatus.value = "Memories exported successfully to ${uri.path}"
                Log.i("SettingsViewModel", "Memories exported to $uri")
            } catch (e: Exception) {
                Log.e("SettingsViewModel", "Error exporting memories", e)
                _errorStatus.value = "Export failed: ${e.message}"
            }
        }
    }

    fun importMemories(uri: Uri) {
        viewModelScope.launch {
            try {
                val contentResolver = getApplication<Application>().contentResolver
                contentResolver.openInputStream(uri)?.use { inputStream ->
                    BufferedReader(InputStreamReader(inputStream)).use { reader ->
                        val jsonString = reader.readText()
                        val typeToken = object : TypeToken<List<ConversationMemory>>() {}.type
                        val memories: List<ConversationMemory> = gson.fromJson(jsonString, typeToken)

                        var importedCount = 0
                        var skippedCount = 0
                        memories.forEach { memory ->
                            // Simple import: insert all. Could add conflict resolution or checks.
                            // Forcing id to 0 to ensure new ID is generated by Room on insert.
                            val newId = conversationDao.insertMemory(memory.copy(id = 0))
                            if (newId > 0) importedCount++ else skippedCount++
                        }
                        _operationStatus.value = "Import complete. Imported: $importedCount, Skipped/Updated: $skippedCount"
                        Log.i("SettingsViewModel", "Memories imported from $uri. Imported: $importedCount, Skipped: $skippedCount")
                    }
                } ?: run {
                    _errorStatus.value = "Failed to open input stream for import."
                }
            } catch (e: Exception) {
                Log.e("SettingsViewModel", "Error importing memories", e)
                _errorStatus.value = "Import failed: ${e.message}"
            }
        }
    }

    fun resetMemory() {
        viewModelScope.launch {
            try {
                conversationDao.clearAllMemories()
                _operationStatus.value = "All memories have been reset."
                Log.i("SettingsViewModel", "Memory reset successfully.")
            } catch (e: Exception) {
                Log.e("SettingsViewModel", "Error resetting memory", e)
                _errorStatus.value = "Reset failed: ${e.message}"
            }
        }
    }

    fun clearStatusMessages() {
        _operationStatus.value = null
        _errorStatus.value = null
    }
}
